[package]
name = "divide_and_conquer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dev-dependencies]
rand = { version = "0.8.5", features = ["min_const_gen"] }

[dependencies]
